### ISSUE TITLE
Coverage of Blockchain Explorers

### ISSUE THREAD

**Issue by prastut** [avisrivastava254084/zcash_service_status_dashboad#5]
# Coverage of Blockchain Explorers

## Explorers Getting Monitored
* https://explorer.zcha.in/
* https://zcashnetwork.info/
* https://explorer.zcashfr.io/
* https://explorer.zecmate.com/
* https://chain.so/ZEC
* https://live-sochain-blockioinc.netdna-ssl.com/zcash

Total: 6

## Parameters getting Monitored: 

* Blockchain height across all explorers. 
* Transaction tally in the last block across all explorers.  
* Downtime check of Blockchain Explorers.
      

      
## Methodology
* Since we can't single out a blockhain explorer for checking the data against, we will setup a full node + of ZCash and then use the public APIs of the above explorers to compare them. Our full node's data will be the single source of truth and the explorers will be compared with that.
* UX for blockchain explorers will be figured out while execution. 
* Tech Infrastructure:
    * Server specs: 8GB RAM, 4 CPU, Ubuntu Machine. 
    * Cost: 
        * $40/month
        * $480/year. 

#### API Links: 
Documenting API links, since for most explorers, documentation is not available/poorly documented/or gives 404: 
* ZCha Explorer API Link: https://explorer.zcha.in/api
* Chain.so Explorer API Link: https://chain.so/api/v2/block/ZEC/594351

* ExplorerZECMate API Link: 
    * Sync Status: https://explorer.zecmate.com/api/sync
    * Get Transaction Details:  https://explorer.zecmate.com/api/tx/0b0ddb4fe03a19b2f579a7ba35320e4102b413c5d6d38b615b479f49da944ca2
    * Get Block Summary: https://explorer.zecmate.com/api/blocks?limit=3&blockDate=2019-08-30
* zcashnetwork.info: https://zcashnetwork.info/api/tx/0b0ddb4fe03a19b2f579a7ba35320e4102b413c5d6d38b615b479f49da944ca2
* https://live-sochain-blockioinc.netdna-ssl.com/api/v2/block/ZEC/594351

#### Explorers that we are unable to monitor: 

1. https://minergate.com/blockchain/zec/blocks. Reason: [Discontinued API](https://api.minergate.com/1.0/zec/status). 
2. https://zcash.plutomonkey.com/. Reason: Explorer is down.

**Comment by avisrivastava254084** [comment]
@Lord-of-Codes 
Can you explain here why there are so many downs(0) while monitoring block explorers in all the panels?

**Comment by kebab-mai-haddi** [comment]
@prastut 

#update

One issue referenced in Tromer's feedback was frequent downs(0s) while checking the last block. The most probable cause can be fault in their (BCEs) APIs. @Lord-of-Codes tried increasing the request timeout but in vain. Although, he will update here after regressive testing and then we will be able to decide what to do next.

Even doing some hacks, @Lord-of-Codes and I think we should put a disclaimer in the panel that most probable cause could be a broken API.

ETA of updating the results of regressive testing: Sat, Nov 17, 2019, 6PM IST.

@Lord-of-Codes you can post the results directly here.

**Comment by prastut** [comment]
@avisrivastava254084 

There are two buckets I see the issue falling into: 
1. Data not received. 
2. Data received but sanity check fails. 

Can both the buckets be treated differently on the panels? For eg: In the panels under the Chain Metrics Check group, when hovering over the data on any panel, instead of showing a binary 0 and 1, we can show the following information: 
1. 0 due to API being down -> Show "API is down" on the tooltip.
2. 0 due to sanity check failing -> Show "Sanity check failed" on the tooltip.

**Comment by Lord-of-Codes** [comment]
@prastut 

I think we don't need to do that because its already mentioned in the description of Block Height Check and Block Contents Check panels that they will plot 0 if the Blockchain Explorer is down. 

So, it will be pretty self explanatory that, say if, Block Height Check of zcha is showing 0 then its 
a) because the blockchain explorer is down if it shows so in the other graph
b) else the block height is not current

Another thing is, I don't think grafana has the functionality of adding dynamic data to the tooltip, but I'm not completely sure about this. @avisrivastava254084 help me out on this.

**Comment by prastut** [comment]
@Lord-of-Codes I understand where you are coming from and on the same page that it's logical to keep the panels as they are. Use the following triggers cognizant with time axis underneath i.e if it feels like it will take > 3 days to solve what I am proposing, then we should ignore this and let the community feedbacks roll in. 

My PoV: 
People are not always logical and rational, especially consumer-facing experiences where the norm is to deal with irrationality. Get into the shoes of an average joe who is interested in the world of crypto. 

> I don't think grafana has the functionality of adding dynamic data to the tooltip

These are just constraints. Even though I have incomplete awareness of what Grafana can do and not do, there is a probability that Grafana renders whatever data we send from the backend and data can be modified at an intermediary step in the process.

**Comment by Lord-of-Codes** [comment]
@prastut I concur with the part that we should explicitly mention the cause of the sanity check failing.

The problem is with implementing that using Grafana. What's happening right now is that only float values are being sent to Grafana and it plots them and generates a tooltip for it automatically without accepting additional input. 

Let me see if I can find out an extension or a hack for implementing the solution (without having to make changes to Grafana's code because its written mostly in Go and it would definitely take more than 3 days to figure out). I'll report here by eod tomorrow (ist).

**Comment by prastut** [comment]
@Lord-of-Codes probably this might help: 

https://grafana.com/docs/reference/annotations/

We can layer context on top of the existing data.

How I reached here: 
1. Googled "display charts with strings as values grafana"
2. Landed on this: https://community.grafana.com/t/show-string-and-time-fields-from-influx-on-a-single-graph/4973
3. Got context that there is a way to overlay context.

**Comment by Lord-of-Codes** [comment]
@prastut Thanks. This looks promising.

**Comment by Lord-of-Codes** [comment]
@prastut I am afraid annotations wouldn't satisfy our purpose. Annotations are used to mark and describe specific points or ranges in the panel as a whole (example - update from v2.1.1 to v2.1.2 at a specific time in the difficulty metric panel), it cannot add value to the tooltips of the graphs contained in the panel.

I also found these two links -
https://community.grafana.com/t/customize-tooltip-text/8214
https://community.grafana.com/t/can-i-add-more-info-to-tooltips/88

These are old but I believe the case is still the same. I also couldn't find any plugin that could enable us to do what we are looking to do. 

As an aside, I could raise a feature request for the same(I couldn't find any issue describing work being done on this topic in the issue tracker at first search).

**Comment by prastut** [comment]
> it cannot add value to the tooltips of the graphs contained in the panel.

Hmm it seems that you are operating in the constraint that is given. The issue is not that we need to make tooltips better, the issue is to solve the user problem of getting clarity around why sanity check is failing by any means possible. Any tool/solution is just an answer to that question. 

Can annotation now solve the user problem?

**Comment by Lord-of-Codes** [comment]
@prastut Okay. I see what you mean. Sorry, that i didn't get you earlier. I'll formulate and implement a solution today.

**Comment by Lord-of-Codes** [comment]
@prastut @avisrivastava254084 There are some other things that could use better implementation in the project. I'll list them out today, here.

**Comment by Lord-of-Codes** [comment]
Hey, sorry for the delayed response. I am working on the annotations solution and have run into some problems regarding automating them. It might take some more time to get it working.

**Comment by prastut** [comment]
@Lord-of-Codes do have an ETA for awareness?

**Comment by Lord-of-Codes** [comment]
@prastut I have abandoned the annotations approach after sufficient experimenting. As I had earlier suspected, it would not fulfil the requirements.

Attached are snapshots of the graph to illustrate why -
1. [Attempt to annotate first 20 minutes of a graph](http://149.28.197.86:3000/dashboard/snapshot/V1xvhGzqmV258v2UHYH22Wi5hjQttFx0?orgId=1)
2. [Same graph but zoomed in this time](http://149.28.197.86:3000/dashboard/snapshot/vWTK1lJT9au79ulG87ezsz1HoMM3Nl0v?orgId=1)

As you can see,
1. The data is revealed only when, one hovers over the annotation symbol.
2. This hides the tooltip, so you can not cross-reference information at the same exact moment.
3. Not the most efficient way to deliver information in our case since the would annotations start overlapping and become illegible (this is how the first graph will [look](http://149.28.197.86:3000/d/DyDEf8AZk/blockchain-explorers?orgId=1&from=1574620200000&to=1574641799000), in normal dashboard view). So, if the entire graph is annotated in such a way, no useful information will be conveyed due to all the overcrowding.

A better approach would be one as used in the [Exchanges dashboard](https://zcashservicestatus.info/d/n-3yUXNWk/exchanges?orgId=1). I have created a sample [dashboard](http://149.28.197.86:3000/d/DyDEf8AZk/blockchain-explorers?orgId=1) with 2 blockchain explorers in a local instance. It lists specific dashboards which convey detailed information using singlestat objects (as opposed to a graph). 

Let me know what you think of this method.

**Comment by Lord-of-Codes** [comment]
A very basic question I have is, why are we using a graph to plot a binary entity (block height check and last block check) as opposed to using a singlestat object?

**Comment by prastut** [comment]
> As I had earlier suspected, it would not fulfil the requirements.

Makes sense, though I think extra work is being done here. You could have just tried with one annotation and sent a screenshot of how it looks, and the same reasons would have come to light there. I respect the hustle in terms of working towards automating it, but time could have been saved in not going down that route. 

>  have created a sample dashboard with 2 blockchain explorers in a local instance.

Not able to access this dashboard

> (block height check and last block check) as opposed to using a singlestat object?

Does this graph visualizes failure check with a time axis underneath?

**Comment by Lord-of-Codes** [comment]
>but time could have been saved in not going down that route

yes, right. sorry

>Not able to access this dashboard

Check your mail.

>Does this graph visualizes failure check with a time axis underneath?

No, it doesn't. It only displays the current failure check. Its not really a graph but a text box tbh. 
Do we need to display failure check with reference to time? Current failure check with a percentage meter aggregating historical failure percentage should suffice imo.
